BEGIN;

-- Backfill inconsistent language codes in metadata so that the languages
-- endpoint (and language filters) no longer treat e.g. 'eng', 'English' and
-- 'en' as separate languages.
--
-- The mapping below is generated from pycountry and covers ISO 639-2/3 codes
-- (terminological and bibliographic) plus English language names -> ISO 639-1.
-- It mirrors core.analysis.language_id.normalize_language_code, which now
-- normalises languages on write, so this backfill is a one-off cleanup of
-- historic data.

CREATE TEMP TABLE lang_map (
    key text PRIMARY KEY,
    alpha2 text NOT NULL
) ON COMMIT DROP;

INSERT INTO lang_map (key, alpha2) VALUES
    ('aar', 'aa'),
    ('abk', 'ab'),
    ('abkhazian', 'ab'),
    ('afar', 'aa'),
    ('afr', 'af'),
    ('afrikaans', 'af'),
    ('aka', 'ak'),
    ('akan', 'ak'),
    ('alb', 'sq'),
    ('albanian', 'sq'),
    ('amh', 'am'),
    ('amharic', 'am'),
    ('ara', 'ar'),
    ('arabic', 'ar'),
    ('aragonese', 'an'),
    ('arg', 'an'),
    ('arm', 'hy'),
    ('armenian', 'hy'),
    ('asm', 'as'),
    ('assamese', 'as'),
    ('ava', 'av'),
    ('avaric', 'av'),
    ('ave', 'ae'),
    ('avestan', 'ae'),
    ('aym', 'ay'),
    ('aymara', 'ay'),
    ('aze', 'az'),
    ('azerbaijani', 'az'),
    ('bak', 'ba'),
    ('bam', 'bm'),
    ('bambara', 'bm'),
    ('bangla', 'bn'),
    ('baq', 'eu'),
    ('bashkir', 'ba'),
    ('basque', 'eu'),
    ('bel', 'be'),
    ('belarusian', 'be'),
    ('ben', 'bn'),
    ('bengali', 'bn'),
    ('bis', 'bi'),
    ('bislama', 'bi'),
    ('bod', 'bo'),
    ('bos', 'bs'),
    ('bosnian', 'bs'),
    ('bre', 'br'),
    ('breton', 'br'),
    ('bul', 'bg'),
    ('bulgarian', 'bg'),
    ('bur', 'my'),
    ('burmese', 'my'),
    ('castilian', 'es'),
    ('cat', 'ca'),
    ('catalan', 'ca'),
    ('ces', 'cs'),
    ('cha', 'ch'),
    ('chamorro', 'ch'),
    ('che', 'ce'),
    ('chechen', 'ce'),
    ('chi', 'zh'),
    ('chichewa', 'ny'),
    ('chinese', 'zh'),
    ('chu', 'cu'),
    ('church slavic', 'cu'),
    ('chuvash', 'cv'),
    ('chv', 'cv'),
    ('cor', 'kw'),
    ('cornish', 'kw'),
    ('corsican', 'co'),
    ('cos', 'co'),
    ('cre', 'cr'),
    ('cree', 'cr'),
    ('croatian', 'hr'),
    ('cym', 'cy'),
    ('cze', 'cs'),
    ('czech', 'cs'),
    ('dan', 'da'),
    ('danish', 'da'),
    ('deu', 'de'),
    ('div', 'dv'),
    ('divehi', 'dv'),
    ('dut', 'nl'),
    ('dutch', 'nl'),
    ('dzo', 'dz'),
    ('dzongkha', 'dz'),
    ('ell', 'el'),
    ('eng', 'en'),
    ('english', 'en'),
    ('epo', 'eo'),
    ('esperanto', 'eo'),
    ('est', 'et'),
    ('estonian', 'et'),
    ('eus', 'eu'),
    ('ewe', 'ee'),
    ('fao', 'fo'),
    ('faroese', 'fo'),
    ('farsi', 'fa'),
    ('fas', 'fa'),
    ('fij', 'fj'),
    ('fijian', 'fj'),
    ('fin', 'fi'),
    ('finnish', 'fi'),
    ('flemish', 'nl'),
    ('fra', 'fr'),
    ('fre', 'fr'),
    ('french', 'fr'),
    ('fry', 'fy'),
    ('ful', 'ff'),
    ('fulah', 'ff'),
    ('galician', 'gl'),
    ('ganda', 'lg'),
    ('geo', 'ka'),
    ('georgian', 'ka'),
    ('ger', 'de'),
    ('german', 'de'),
    ('gla', 'gd'),
    ('gle', 'ga'),
    ('glg', 'gl'),
    ('glv', 'gv'),
    ('gre', 'el'),
    ('greek', 'el'),
    ('grn', 'gn'),
    ('guarani', 'gn'),
    ('guj', 'gu'),
    ('gujarati', 'gu'),
    ('haitian', 'ht'),
    ('hat', 'ht'),
    ('hau', 'ha'),
    ('hausa', 'ha'),
    ('hbs', 'sh'),
    ('heb', 'he'),
    ('hebrew', 'he'),
    ('her', 'hz'),
    ('herero', 'hz'),
    ('hin', 'hi'),
    ('hindi', 'hi'),
    ('hiri motu', 'ho'),
    ('hmo', 'ho'),
    ('hrv', 'hr'),
    ('hun', 'hu'),
    ('hungarian', 'hu'),
    ('hye', 'hy'),
    ('ibo', 'ig'),
    ('ice', 'is'),
    ('icelandic', 'is'),
    ('ido', 'io'),
    ('igbo', 'ig'),
    ('iii', 'ii'),
    ('iku', 'iu'),
    ('ile', 'ie'),
    ('ina', 'ia'),
    ('ind', 'id'),
    ('indonesian', 'id'),
    ('interlingua (international auxiliary language association)', 'ia'),
    ('interlingue', 'ie'),
    ('inuktitut', 'iu'),
    ('inupiaq', 'ik'),
    ('ipk', 'ik'),
    ('irish', 'ga'),
    ('isl', 'is'),
    ('ita', 'it'),
    ('italian', 'it'),
    ('japanese', 'ja'),
    ('jav', 'jv'),
    ('javanese', 'jv'),
    ('jpn', 'ja'),
    ('kal', 'kl'),
    ('kalaallisut', 'kl'),
    ('kan', 'kn'),
    ('kannada', 'kn'),
    ('kanuri', 'kr'),
    ('kas', 'ks'),
    ('kashmiri', 'ks'),
    ('kat', 'ka'),
    ('kau', 'kr'),
    ('kaz', 'kk'),
    ('kazakh', 'kk'),
    ('khm', 'km'),
    ('khmer', 'km'),
    ('kik', 'ki'),
    ('kikuyu', 'ki'),
    ('kin', 'rw'),
    ('kinyarwanda', 'rw'),
    ('kir', 'ky'),
    ('kirghiz', 'ky'),
    ('kom', 'kv'),
    ('komi', 'kv'),
    ('kon', 'kg'),
    ('kongo', 'kg'),
    ('kor', 'ko'),
    ('korean', 'ko'),
    ('kua', 'kj'),
    ('kuanyama', 'kj'),
    ('kur', 'ku'),
    ('kurdish', 'ku'),
    ('lao', 'lo'),
    ('lat', 'la'),
    ('latin', 'la'),
    ('latvian', 'lv'),
    ('lav', 'lv'),
    ('lim', 'li'),
    ('limburgan', 'li'),
    ('lin', 'ln'),
    ('lingala', 'ln'),
    ('lit', 'lt'),
    ('lithuanian', 'lt'),
    ('ltz', 'lb'),
    ('lub', 'lu'),
    ('luba-katanga', 'lu'),
    ('lug', 'lg'),
    ('luxembourgish', 'lb'),
    ('mac', 'mk'),
    ('macedonian', 'mk'),
    ('mah', 'mh'),
    ('mal', 'ml'),
    ('malagasy', 'mg'),
    ('malay (macrolanguage)', 'ms'),
    ('malayalam', 'ml'),
    ('maltese', 'mt'),
    ('mandarin', 'zh'),
    ('manx', 'gv'),
    ('mao', 'mi'),
    ('maori', 'mi'),
    ('mar', 'mr'),
    ('marathi', 'mr'),
    ('marshallese', 'mh'),
    ('may', 'ms'),
    ('mkd', 'mk'),
    ('mlg', 'mg'),
    ('mlt', 'mt'),
    ('modern greek (1453-)', 'el'),
    ('mon', 'mn'),
    ('mongolian', 'mn'),
    ('mri', 'mi'),
    ('msa', 'ms'),
    ('mya', 'my'),
    ('nau', 'na'),
    ('nauru', 'na'),
    ('nav', 'nv'),
    ('navajo', 'nv'),
    ('nbl', 'nr'),
    ('nde', 'nd'),
    ('ndo', 'ng'),
    ('ndonga', 'ng'),
    ('nep', 'ne'),
    ('nepali (macrolanguage)', 'ne'),
    ('nld', 'nl'),
    ('nno', 'nn'),
    ('nob', 'nb'),
    ('nor', 'no'),
    ('north ndebele', 'nd'),
    ('northern sami', 'se'),
    ('norwegian', 'no'),
    ('norwegian bokmål', 'nb'),
    ('norwegian nynorsk', 'nn'),
    ('nya', 'ny'),
    ('occitan (post 1500)', 'oc'),
    ('oci', 'oc'),
    ('odia', 'or'),
    ('oji', 'oj'),
    ('ojibwa', 'oj'),
    ('ori', 'or'),
    ('oriya', 'or'),
    ('oriya (macrolanguage)', 'or'),
    ('orm', 'om'),
    ('oromo', 'om'),
    ('oss', 'os'),
    ('ossetian', 'os'),
    ('pali', 'pi'),
    ('pan', 'pa'),
    ('panjabi', 'pa'),
    ('per', 'fa'),
    ('persian', 'fa'),
    ('pli', 'pi'),
    ('pol', 'pl'),
    ('polish', 'pl'),
    ('por', 'pt'),
    ('portuguese', 'pt'),
    ('punjabi', 'pa'),
    ('pus', 'ps'),
    ('pushto', 'ps'),
    ('que', 'qu'),
    ('quechua', 'qu'),
    ('roh', 'rm'),
    ('romanian', 'ro'),
    ('romansh', 'rm'),
    ('ron', 'ro'),
    ('rum', 'ro'),
    ('run', 'rn'),
    ('rundi', 'rn'),
    ('rus', 'ru'),
    ('russian', 'ru'),
    ('sag', 'sg'),
    ('samoan', 'sm'),
    ('san', 'sa'),
    ('sango', 'sg'),
    ('sanskrit', 'sa'),
    ('sardinian', 'sc'),
    ('scottish gaelic', 'gd'),
    ('serbian', 'sr'),
    ('serbo-croatian', 'sh'),
    ('shona', 'sn'),
    ('sichuan yi', 'ii'),
    ('sin', 'si'),
    ('sindhi', 'sd'),
    ('sinhala', 'si'),
    ('slk', 'sk'),
    ('slo', 'sk'),
    ('slovak', 'sk'),
    ('slovenian', 'sl'),
    ('slv', 'sl'),
    ('sme', 'se'),
    ('smo', 'sm'),
    ('sna', 'sn'),
    ('snd', 'sd'),
    ('som', 'so'),
    ('somali', 'so'),
    ('sot', 'st'),
    ('south ndebele', 'nr'),
    ('southern sotho', 'st'),
    ('spa', 'es'),
    ('spanish', 'es'),
    ('sqi', 'sq'),
    ('srd', 'sc'),
    ('srp', 'sr'),
    ('ssw', 'ss'),
    ('sun', 'su'),
    ('sundanese', 'su'),
    ('swa', 'sw'),
    ('swahili (macrolanguage)', 'sw'),
    ('swati', 'ss'),
    ('swe', 'sv'),
    ('swedish', 'sv'),
    ('tagalog', 'tl'),
    ('tah', 'ty'),
    ('tahitian', 'ty'),
    ('tajik', 'tg'),
    ('tam', 'ta'),
    ('tamil', 'ta'),
    ('tat', 'tt'),
    ('tatar', 'tt'),
    ('tel', 'te'),
    ('telugu', 'te'),
    ('tgk', 'tg'),
    ('tgl', 'tl'),
    ('tha', 'th'),
    ('thai', 'th'),
    ('tib', 'bo'),
    ('tibetan', 'bo'),
    ('tigrinya', 'ti'),
    ('tir', 'ti'),
    ('ton', 'to'),
    ('tonga (tonga islands)', 'to'),
    ('tsn', 'tn'),
    ('tso', 'ts'),
    ('tsonga', 'ts'),
    ('tswana', 'tn'),
    ('tuk', 'tk'),
    ('tur', 'tr'),
    ('turkish', 'tr'),
    ('turkmen', 'tk'),
    ('twi', 'tw'),
    ('uig', 'ug'),
    ('uighur', 'ug'),
    ('ukr', 'uk'),
    ('ukrainian', 'uk'),
    ('urd', 'ur'),
    ('urdu', 'ur'),
    ('uzb', 'uz'),
    ('uzbek', 'uz'),
    ('ven', 've'),
    ('venda', 've'),
    ('vie', 'vi'),
    ('vietnamese', 'vi'),
    ('vol', 'vo'),
    ('volapük', 'vo'),
    ('walloon', 'wa'),
    ('wel', 'cy'),
    ('welsh', 'cy'),
    ('western frisian', 'fy'),
    ('wln', 'wa'),
    ('wol', 'wo'),
    ('wolof', 'wo'),
    ('xho', 'xh'),
    ('xhosa', 'xh'),
    ('yid', 'yi'),
    ('yiddish', 'yi'),
    ('yor', 'yo'),
    ('yoruba', 'yo'),
    ('zha', 'za'),
    ('zho', 'zh'),
    ('zhuang', 'za'),
    ('zul', 'zu'),
    ('zulu', 'zu');

-- videos: map known ISO 639-2/3 codes and language names to two letter codes.
UPDATE videos AS t
SET metadata = jsonb_set(t.metadata, '{language}', to_jsonb(m.alpha2))
FROM lang_map AS m
WHERE btrim(lower(t.metadata->>'language')) = m.key;

-- videos: normalise case and surrounding whitespace on any remaining values.
UPDATE videos AS t
SET metadata = jsonb_set(t.metadata, '{language}', to_jsonb(btrim(lower(t.metadata->>'language'))))
WHERE t.metadata ? 'language'
  AND t.metadata->>'language' <> btrim(lower(t.metadata->>'language'));

-- transcript_sentences: map known ISO 639-2/3 codes and language names to two letter codes.
UPDATE transcript_sentences AS t
SET metadata = jsonb_set(t.metadata, '{language}', to_jsonb(m.alpha2))
FROM lang_map AS m
WHERE btrim(lower(t.metadata->>'language')) = m.key;

-- transcript_sentences: normalise case and surrounding whitespace on any remaining values.
UPDATE transcript_sentences AS t
SET metadata = jsonb_set(t.metadata, '{language}', to_jsonb(btrim(lower(t.metadata->>'language'))))
WHERE t.metadata ? 'language'
  AND t.metadata->>'language' <> btrim(lower(t.metadata->>'language'));

-- video_claims: map known ISO 639-2/3 codes and language names to two letter codes.
UPDATE video_claims AS t
SET metadata = jsonb_set(t.metadata, '{language}', to_jsonb(m.alpha2))
FROM lang_map AS m
WHERE btrim(lower(t.metadata->>'language')) = m.key;

-- video_claims: normalise case and surrounding whitespace on any remaining values.
UPDATE video_claims AS t
SET metadata = jsonb_set(t.metadata, '{language}', to_jsonb(btrim(lower(t.metadata->>'language'))))
WHERE t.metadata ? 'language'
  AND t.metadata->>'language' <> btrim(lower(t.metadata->>'language'));

COMMIT;
