DEFAULT_KEYWORDS: dict[str, list[str]] = {
    "Climate": [
        "sequía",
        "HAARP",
        "geoingeniería",
        "chemtrails",
        "yoduro de plata",
        "cambio climático",
        "fumigaciones",
        "hielo ártico",
        "hielo antártico",
        "glaciación",
        "deshielo",
        "CO2",
        "alarmismo climático",
    ],
    "Conflicts": [
        "drones",
        "misiles",
        "mercenarios",
        "ejecuciones",
        "pallywood",
        "banderitas",
        "ukronazis",
        "bombardeo",
        "guerra mundial",
        "balcanización",
        "masacres",
        "genocidio",
        "otanistas",
    ],
    "European Union": [
        "fondos europeos",
        "Bruselas",
        "Von de Leyen",
        "OTAN",
        "Parlamento Europeo",
        "Agenda 2030",
        "Ciudad 15 minutos",
        "euro digital",
        "PAC (Política Agraria Común)",
        "Pacto Verde Europeo",
    ],
    "Health": [
        "vacunas",
        "inflamación",
        "grafeno",
        "5G",
        "autismo",
        "cáncer",
        "diabetes",
        "remedios",
        "colesterol",
        "ivermectina",
        "ondas",
        "hormonas",
    ],
    "Migration": [
        "magrebíes",
        "jovenlandeses",
        "marroquíes",
        "inmigrantes",
        "paguitas",
        "musulmanes",
        "islam",
        "moros",
        "rumanos",
        "senegaleses",
        "argelinos",
        "pateras",
        "cayucos",
        "menas",
        "invasión",
    ],
}
