DEFAULT_KEYWORDS: dict[str, list[str]] = {
    "db3d996b-e691-4ce5-8c46-e35a82a9b28c": [
        "sequía",
        "HAARP",
        "geoingeniería",
        "chemtrails",
        "yoduro de plata",
        "cambio climático",
        "fumigaciones",
        "hielo ártico",
        "hielo antártico",
        "glaciación",
        "deshielo",
        "CO2",
        "alarmismo climático",
    ],  # Climate
    "0d7aaf8d-5b7e-4c0c-b03a-28457e27ac7d": [
        "drones",
        "misiles",
        "mercenarios",
        "ejecuciones",
        "pallywood",
        "banderitas",
        "ukronazis",
        "bombardeo",
        "guerra mundial",
        "balcanización",
        "masacres",
        "genocidio",
        "otanistas",
    ],  # Conflicts
    "ff1bedb9-43e4-49e6-9c3f-27babfb7bfa1": [
        "fondos europeos",
        "Bruselas",
        "Von de Leyen",
        "OTAN",
        "Parlamento Europeo",
        "Agenda 2030",
        "Ciudad 15 minutos",
        "euro digital",
        "PAC (Política Agraria Común)",
        "Pacto Verde Europeo",
    ],  # European Union
    "bb52f622-b9ee-4d5b-9b70-5fd05046528b": [
        "vacunas",
        "inflamación",
        "grafeno",
        "5G",
        "autismo",
        "cáncer",
        "diabetes",
        "remedios",
        "colesterol",
        "ivermectina",
        "ondas",
        "hormonas",
    ],  # Health
    "3cd4a9cd-5906-4b0b-9167-57ff22c2345a": [
        "magrebíes",
        "jovenlandeses",
        "marroquíes",
        "inmigrantes",
        "paguitas",
        "musulmanes",
        "islam",
        "moros",
        "rumanos",
        "senegaleses",
        "argelinos",
        "pateras",
        "cayucos",
        "menas",
        "invasión",
    ],  # Migration
}
