apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert-prod
spec:
  domains:
    - prebunking.efcsn.com
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-backend-config
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    requestPath: /login
    port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: pas-static-ip
    networking.gke.io/managed-certificates: managed-cert
  labels:
    app: frontend
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
  annotations:
    cloud.google.com/backend-config: '{"ports": {"3000":"frontend-backend-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: frontend
    tier: web
  ports:
    - port: 3000
