apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  annotations:
    iam.gke.io/gcp-service-account: workload-identity-sa@pas-production-1.iam.gserviceaccount.com
# gcloud projects add-iam-policy-binding --project pas-production-1 projects/pas-production-1 \
#     --role=roles/cloudsql.user\
#     --member=principal://iam.googleapis.com/projects/797977642879/locations/global/workloadIdentityPools/pas-production-1.svc.id.goog/subject/ns/default/sa/workload-identity-sa \
#     --condition=None

# gcloud iam service-accounts add-iam-policy-binding --project pas-production-1 workload-identity-sa@pas-production-1.iam.gserviceaccount.com \
#     --role roles/iam.workloadIdentityUser \
#     --member "serviceAccount:pas-production-1.svc.id.goog[default/workload-identity-sa]"
