apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api
  labels:
    app: core-api
spec:
  selector:
    matchLabels:
      app: core-api
      tier: web
  template:
    metadata:
      labels:
        app: core-api
        tier: web
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: core-api
          image: europe-west4-docker.pkg.dev/pas-shared/pas/core-api:v0.5.0-dev.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: DATABASE_HOST
              value: 127.0.0.1
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: prebunker
            - name: DATABASE_NAME
              value: pas-vectordb
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
            - name: NARRATIVES_BASE_ENDPOINT
              value: https://pas-narratives.fundacionmaldita.es
            - name: APP_BASE_URL
              value: https://pas-dev.fullfact.org
            - name: API_KEYS
              valueFrom:
                secretKeyRef:
                  name: core-api-keys
                  key: keys
            - name: NARRATIVES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: narratives
                  key: api-key
            - name: GEMINI_PROJECT
              value: pas-development-1
            - name: GEMINI_LOCATION
              value: global
            - name: GEMINI_MODEL
              value: gemini-2.0-flash-lite-001
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.17.1
          args:
            - "--private-ip"
            - "--auto-iam-authn"
            - "--structured-logs"
            - "--port=5432"
            - "pas-development-1:europe-west4:pas-vectordb-instance"
          securityContext:
            runAsNonRoot: true
