apiVersion: batch/v1
kind: CronJob
metadata:
  name: core-api-process-alerts
spec:
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: cloud-sql-proxy
              args:
                - "--private-ip"
                - "--auto-iam-authn"
                - "--structured-logs"
                - "--port=5432"
                - "pas-development-1:europe-west4:pas-vectordb-instance"
          containers:
            - name: process-alerts
              env:
                - name: APP_BASE_URL
                  value: https://pas-dev.fullfact.org
                - name: VIDEO_STORAGE_BUCKET_NAME
                  value: pas-prototyping-storage
                - name: EMAIL_FROM
                  value: "auto@fullfact.org"
                - name: GEMINI_PROJECT
                  value: pas-development-1
