apiVersion: batch/v1
kind: CronJob
metadata:
  name: core-api-process-alerts
spec:
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: cloud-sql-proxy
              args:
                - "--private-ip"
                - "--auto-iam-authn"
                - "--structured-logs"
                - "--port=5432"
                - "pas-production-1:europe-west4:pas-vectordb-instance"
          containers:
            - name: process-alerts
              env:
                - name: APP_BASE_URL
                  value: https://prebunking.efcsn.com
                - name: VIDEO_STORAGE_BUCKET_NAME
                  value: pas-production-storage
                - name: EMAIL_FROM
                  value: "no-reply@mail.prebunking.efcsn.com"
                - name: GEMINI_PROJECT
                  value: pas-production-1
                - name: MAILGUN_DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: mailgun
                      key: domain
                - name: MAILGUN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: mailgun
                      key: api-key
